# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '4.x'
    
- task: NuGetAuthenticate@0
  inputs:
    forceReinstallCredentialProvider: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'